const token=localStorage.getItem('LF_TOKEN'),byId=id=>document.getElementById(id),pages={overview:'Обзор',mini:'Mini App',clients:'Клиенты',settings:'Настройки'};
const api=async(url,options={})=>{options.headers={...(options.headers||{}),Authorization:'Bearer '+token};const response=await fetch(url,options),data=await response.json().catch(()=>({}));if(response.status===401){localStorage.removeItem('LF_TOKEN');location.href='/auth.html';throw Error('Сессия завершена')}if(!response.ok)throw Error(data.error||`Ошибка сервера (${response.status})`);return data};
let user={name:'Владелец',company:'LoyaltyFlow',status:'trial',trialEnd:null},state={design:{},connected:false,botUsername:'',appUrl:'',updatedAt:null};
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),initials=value=>String(value||'В').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase(),formatDate=value=>value?new Date(value).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'Ещё не сохранялось',daysLeft=date=>date?Math.max(0,Math.ceil((new Date(date)-Date.now())/86400000))+' дн.':'7 дней';
function showPage(name){if(name==='catalog'){location.href='/catalog-admin.html';return}if(!pages[name])name='overview';document.querySelectorAll('.page').forEach(x=>x.hidden=x.id!==name+'Page');document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===name));byId('pageTitle').textContent=pages[name];location.hash=name==='overview'?'':name;byId('sidebar').classList.remove('open');scrollTo({top:0})}
function toast(text){const node=document.createElement('div');node.className='toast';node.textContent=text;document.body.append(node);setTimeout(()=>node.remove(),2200)}
function botUrl(){const username=String(state.botUsername||'').replace(/^@/,'');return username?'https:'+'//t.me/'+encodeURIComponent(username):''}
function openBot(){const url=botUrl();if(!url)return toast('Сначала подключите Telegram-бота');window.open(url,'_blank','noopener')}
function designFromForm(){const data=new FormData(byId('miniForm'));return{...state.design,name:String(data.get('name')||'').trim(),title:String(data.get('title')||'').trim(),description:String(data.get('description')||'').trim(),balanceLabel:String(data.get('balanceLabel')||'').trim(),buttonText:String(data.get('buttonText')||'').trim(),qr:!!data.get('qr'),profile:!!data.get('profile'),offers:!!data.get('offers'),history:!!data.get('history'),catalog:!!data.get('catalog')}}
function renderDevice(){const phone=document.querySelector('.phone');if(!phone)return;const app=state.appUrl||'';phone.innerHTML=`<div class="device-island"></div><div class="telegram-bar"><button type="button" aria-label="Назад">‹</button><div class="tg-avatar">${escapeHtml((state.botUsername||'B')[0].toUpperCase())}</div><div><b>${escapeHtml(state.design?.name||state.botUsername||'Mini App')}</b><span>бот</span></div><span class="tg-more">•••</span></div><div class="telegram-app">${app?`<iframe id="miniAppFrame" title="Mini App в Telegram" src="${escapeHtml(app)}"></iframe>`:'<div class="preview-empty"><b>Mini App пока недоступно</b><span>Подключите бота и сохраните настройки.</span></div>'}</div><div class="home-indicator"></div>`}
function refreshPreview(){const frame=byId('miniAppFrame');if(frame)frame.src=frame.src;else renderDevice()}
function fillOverview(){const products=Array.isArray(state.design?.products)?state.design.products:[],steps=1+Number(state.connected)+Number(products.length>0),progress=Math.round(steps/3*100),left=3-steps;byId('welcomeTitle').textContent='Добрый день, '+String(user.name||'').split(' ')[0];byId('launchMetric').textContent=progress+'%';byId('launchHint').textContent=progress===100?'Можно запускать':'Завершите '+left+' '+(left===1?'шаг':'шага');byId('productMetric').textContent=products.length;byId('botMetric').textContent=state.connected?'Да':'Нет';byId('botHint').textContent=state.connected?'@'+(state.botUsername||'подключён'):'Требуется подключение';byId('trialMetric').textContent=daysLeft(user.trialEnd);byId('progressText').textContent=steps+' из 3 шагов';byId('stepAccount').classList.add('done');byId('stepBot').classList.toggle('done',state.connected);byId('stepCatalog').classList.toggle('done',products.length>0);byId('connectionStatus').textContent=state.connected?'Подключён @'+state.botUsername:'Не подключён';byId('connectionStatus').classList.toggle('positive',state.connected);byId('lastSaved').textContent=formatDate(state.updatedAt);byId('catalogPreview').innerHTML=products.length?products.slice(0,3).map(p=>'<div class="mini-product"><b>'+escapeHtml(p.name)+'</b><span>'+Number(p.price||0).toLocaleString('ru-RU')+' ₽ · '+Number(p.stock||0)+' шт.</span></div>').join(''):'<div class="empty-block compact"><div><b>Каталог пуст</b><span>Добавьте первые товары</span></div></div>'}
function fillForm(){const d=state.design||{};for(const key of ['name','title','description','balanceLabel','buttonText'])if(byId(key))byId(key).value=d[key]||'';for(const key of ['qr','profile','offers','history','catalog'])byId(key).checked=d[key]!==false;byId('botState').textContent=state.connected?'Подключён @'+state.botUsername:'Бот не подключён. Введите токен и сохраните.';renderDevice()}
function fillSettings(){byId('settingsName').textContent=user.name||'—';byId('settingsCompany').textContent=user.company||'—';byId('settingsStatus').textContent=user.status==='trial'?'Пробный период':user.status||'—';byId('settingsBot').textContent=state.connected?'@'+state.botUsername:'Не подключён';byId('appUrl').value=botUrl()||state.appUrl||'';byId('companyName').textContent=user.company||'LoyaltyFlow';byId('avatar').textContent=initials(user.name)}
async function saveMini(event){event.preventDefault();const status=byId('saveStatus'),form=byId('miniForm'),design=designFromForm();status.textContent='Сохраняем изменения…';try{const result=await api('/api/v1/owner/miniapp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({botToken:form.botToken.value,design})});state={...state,...result,design,updatedAt:new Date().toISOString()};form.botToken.value='';fillForm();fillOverview();fillSettings();status.textContent='Изменения сохранены';toast('Mini App обновлено')}catch(error){status.textContent='Ошибка: '+error.message}}
const style=document.createElement('link');style.rel='stylesheet';style.href='/admin-preview.css?v=2';document.head.append(style);
for(const button of document.querySelectorAll('[data-page]'))button.addEventListener('click',()=>showPage(button.dataset.page));for(const button of document.querySelectorAll('[data-go]'))button.addEventListener('click',()=>showPage(button.dataset.go));byId('miniForm').addEventListener('submit',saveMini);byId('logo').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;if(file.size>500000)return alert('Логотип должен быть меньше 500 КБ');const reader=new FileReader();reader.onload=()=>{state.design.logo=reader.result};reader.readAsDataURL(file)});byId('logout').onclick=()=>{localStorage.removeItem('LF_TOKEN');location.href='/auth.html'};byId('mobileMenu').onclick=()=>byId('sidebar').classList.toggle('open');byId('openMiniApp').onclick=openBot;byId('settingsOpenApp').onclick=openBot;byId('previewMiniApp').onclick=refreshPreview;byId('copyUrl').onclick=async()=>{const url=botUrl()||state.appUrl;if(!url)return toast('Адрес пока не создан');await navigator.clipboard.writeText(url);toast('Ссылка на бота скопирована')};
async function start(){if(!token){location.href='/auth.html';return}try{[user,state]=await Promise.all([api('/api/v1/auth/me'),api('/api/v1/owner/miniapp')])}catch(error){byId('globalError').hidden=false;byId('globalError').textContent='Не удалось загрузить данные: '+error.message;return}fillForm();fillOverview();fillSettings();showPage(location.hash.slice(1)||'overview')}start();
const enhancements=document.createElement('script');enhancements.src='/admin-enhancements.js?v=4';enhancements.defer=true;document.body.append(enhancements);
const botGuide=document.createElement('script');botGuide.src='/bot-guide.js?v=1';botGuide.defer=true;document.body.append(botGuide);
