let email='';
const captcha={reg:{widgetId:null,ready:false},login:{widgetId:null,ready:false}};
let turnstilePromise=null;
let phoneInstance=null;
let phoneInitPromise=null;
const phoneInput=document.querySelector('#reg input[name="phone"]');
const message=(value,error=false)=>{const host=document.querySelector('#message');if(!host)return;host.replaceChildren();const box=document.createElement('div');box.className='msg'+(error?' error':'');box.textContent=String(value??'');host.appendChild(box)};
async function call(url,body){const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>null);if(!data||!response.ok)throw Error(data?.error||'Сервис временно недоступен');return data}
function tab(name){for(const id of['reg','verify','login'])document.querySelector('#'+id).classList.add('hide');document.querySelector('#'+name).classList.remove('hide');regTab.classList.toggle('on',name==='reg');loginTab.classList.toggle('on',name==='login');if(name==='reg')mountCaptcha('reg');if(name==='login')mountCaptcha('login')}
function detectedCountry(){const locale=(navigator.languages?.[0]||navigator.language||'').replace('_','-'),parts=locale.split('-'),region=parts[1]?.toLowerCase();if(region?.length===2)return region;const language=parts[0].toLowerCase(),fallback={ru:'ru',en:'us',de:'de',fr:'fr',es:'es',it:'it',pt:'br',tr:'tr',uk:'ua',kk:'kz',uz:'uz',zh:'cn',ja:'jp',ko:'kr'}[language];if(fallback)return fallback;return Intl.DateTimeFormat().resolvedOptions().timeZone==='Asia/Yekaterinburg'?'ru':'us'}
function loadPhoneLibrary(){if(window.intlTelInput)return Promise.resolve();return new Promise((resolve,reject)=>{if(!document.querySelector('link[data-intl-phone]')){const link=document.createElement('link');link.rel='stylesheet';link.href='https://cdn.jsdelivr.net/npm/intl-tel-input@29.2.3/dist/css/intlTelInput.min.css';link.dataset.intlPhone='true';document.head.appendChild(link)}const existing=document.querySelector('script[data-intl-phone]');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',()=>reject(Error('Не удалось загрузить список стран')),{once:true});return}const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/intl-tel-input@29.2.3/dist/js/intlTelInput.min.js';script.async=true;script.dataset.intlPhone='true';script.onload=resolve;script.onerror=()=>reject(Error('Не удалось загрузить список стран'));document.head.appendChild(script)})}
async function initPhone(){if(!phoneInput)return;await loadPhoneLibrary();if(!window.intlTelInput)throw Error('Не удалось инициализировать выбор страны');phoneInstance=window.intlTelInput(phoneInput,{initialCountry:detectedCountry(),nationalMode:false,formatAsYouType:true,autoPlaceholder:'aggressive',countrySearch:true,loadUtils:()=>import('https:'+'//cdn.jsdelivr.net/npm/intl-tel-input@29.2.3/dist/js/utils.js')});await phoneInstance.promise.catch(()=>{});const country=phoneInstance.getSelectedCountryData();if(!phoneInput.value&&country?.dialCode)phoneInstance.setNumber('+'+country.dialCode)}
function loadTurnstile(){if(turnstilePromise)return turnstilePromise;turnstilePromise=(async()=>{const response=await fetch('/api/v1/public/registration-config',{cache:'no-store',headers:{accept:'application/json'}});const config=await response.json().catch(()=>null);if(!response.ok||!config?.captchaConfigured||!config.turnstileSiteKey)throw Error('Cloudflare Turnstile не настроен');if(typeof window.turnstile?.render!=='function')await new Promise((resolve,reject)=>{const callbackName='onMainTurnstileLoad';const timeout=setTimeout(()=>{delete window[callbackName];reject(Error('Cloudflare API не ответил вовремя'))},15000);window[callbackName]=()=>{clearTimeout(timeout);delete window[callbackName];typeof window.turnstile?.render==='function'?resolve():reject(Error('Cloudflare API загрузился некорректно'))};const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit&onload='+callbackName;script.async=true;script.onerror=()=>{clearTimeout(timeout);delete window[callbackName];reject(Error('Браузер заблокировал Cloudflare'))};document.head.appendChild(script)});return config.turnstileSiteKey})();return turnstilePromise}
async function mountCaptcha(kind){const state=captcha[kind];if(state.widgetId!==null)return;const form=document.getElementById(kind);const status=form?.querySelector('.captcha-status');const button=form?.querySelector('.submit');if(!form||!status)return;button.disabled=true;try{const sitekey=await loadTurnstile();const selector=kind==='reg'?'#main-register-turnstile-widget':'#main-login-turnstile-widget';state.widgetId=window.turnstile.render(selector,{sitekey,theme:'dark',appearance:'always',execution:'render',size:'normal',action:kind==='reg'?'register':'login',retry:'auto','refresh-expired':'auto',callback:token=>{form.elements.turnstileToken.value=token;state.ready=true;status.textContent='Проверка пройдена'},'expired-callback':()=>{form.elements.turnstileToken.value='';state.ready=false;status.textContent='Поставьте галочку повторно'},'error-callback':code=>{form.elements.turnstileToken.value='';state.ready=false;status.textContent='Ошибка Cloudflare Turnstile: '+String(code||'unknown');return true}});status.textContent='Поставьте галочку «Я не робот»';button.disabled=false}catch(error){status.textContent=error.message;button.disabled=true}}
function requireCaptcha(kind){const state=captcha[kind];if(state.ready)return true;const status=document.getElementById(kind)?.querySelector('.captcha-status');if(status)status.textContent='Подтвердите, что вы не робот';return false}
function resetCaptcha(kind){const state=captcha[kind];state.ready=false;const form=document.getElementById(kind);if(form?.elements.turnstileToken)form.elements.turnstileToken.value='';if(state.widgetId!==null)window.turnstile?.reset(state.widgetId)}
function ensureCaptcha(kind){const form=document.getElementById(kind);if(!form||form.querySelector('.captcha-wrap'))return;const id=kind==='reg'?'main-register-turnstile-widget':'main-login-turnstile-widget';const wrap=document.createElement('div');wrap.className='captcha-wrap';const label=document.createElement('span');label.className='captcha-label';label.textContent='Проверка безопасности';const widget=document.createElement('div');widget.id=id;widget.className='cf-turnstile';const token=document.createElement('input');token.type='hidden';token.name='turnstileToken';const status=document.createElement('div');status.className='captcha-status';status.textContent='Загрузка проверки безопасности…';wrap.append(label,widget,token,status);form.querySelector('.submit').before(wrap)}
const componentStyle=document.createElement('style');componentStyle.textContent='.captcha-wrap{margin-top:16px;min-height:96px;padding:12px;border:1px solid #29313a;border-radius:11px;background:#0d1116}.captcha-label{display:block;margin-bottom:8px;color:#aeb7c0;font-size:12px}.captcha-status{margin-top:6px;color:#87919b;font-size:12px}.cf-turnstile{min-height:65px}.msg.error{border-color:#693c3c;background:#261616;color:#ffb6b6}.iti{width:100%;--iti-border-color:#323b45;--iti-dropdown-bg:#12171c;--iti-hover-color:#1c252d;--iti-dialcode-color:#b8c1ca}.iti input{padding-left:88px!important}.iti__selected-country{min-width:74px;border-right:1px solid #29313a;background:#10151a!important;border-radius:9px 0 0 9px}.iti__selected-country:hover,.iti__selected-country-primary:hover{background:#182027!important}.iti__arrow{border-top-color:#95a1ab!important}.iti__dropdown-content{border:1px solid #34404b!important;border-radius:12px!important;background:#12171c!important;box-shadow:0 18px 48px #000a!important;color:#fff!important}.iti__country{padding:9px 12px!important}.iti__country:hover,.iti__country.iti__highlight{background:#1c252d!important}.iti__search-input{height:40px!important;margin:8px!important;width:calc(100% - 16px)!important;border:1px solid #35414b!important;border-radius:8px!important;background:#0c1115!important;color:#fff!important}@media(max-width:580px){.iti__dropdown-content{position:fixed!important;inset:auto 10px 10px!important;max-height:70dvh!important}}';document.head.appendChild(componentStyle);ensureCaptcha('reg');ensureCaptcha('login');phoneInitPromise=initPhone().catch(error=>{console.error(error);return null});
async function register(event){event.preventDefault();if(!requireCaptcha('reg'))return;await phoneInitPromise;if(!phoneInstance){message('Не удалось загрузить выбор страны. Обновите страницу и попробуйте снова.',true);return}await phoneInstance.promise.catch(()=>{});if(!phoneInstance.isValidNumber()){message('Проверьте код страны и номер телефона.',true);phoneInput?.focus();return}const form=event.target,button=form.querySelector('.submit'),data=Object.fromEntries(new FormData(form));data.phone=phoneInstance.getNumber();button.disabled=true;button.textContent='Отправляем код…';try{const result=await call('/api/v1/auth/register',data);email=data.email;tab('verify');message(result.message)}catch(error){message(error.message,true);button.disabled=false;button.textContent='Зарегистрироваться';resetCaptcha('reg')}}
async function verify(event){event.preventDefault();const button=event.target.querySelector('.submit');button.disabled=true;try{const result=await call('/api/v1/auth/verify',{email,code:new FormData(event.target).get('code')});message(result.message);setTimeout(()=>tab('login'),1200)}catch(error){message(error.message,true);button.disabled=false}}
async function login(event){event.preventDefault();if(!requireCaptcha('login'))return;const form=event.target,button=form.querySelector('.submit');button.disabled=true;button.textContent='Входим…';try{const result=await call('/api/v1/auth/login',Object.fromEntries(new FormData(form)));localStorage.setItem('LF_TOKEN',result.token);location.href='/'}catch(error){message(error.message,true);button.disabled=false;button.textContent='Войти';resetCaptcha('login')}}
mountCaptcha('reg');
