(()=>{
  const form=document.getElementById('loginForm');
  form.noValidate=false;
  const wrap=document.createElement('div');wrap.className='captcha-wrap';const label=document.createElement('span');label.className='captcha-label';label.textContent='Проверка безопасности';const widget=document.createElement('div');widget.id='login-turnstile-widget';widget.className='cf-turnstile';const token=document.createElement('input');token.type='hidden';token.name='turnstileToken';const statusNode=document.createElement('div');statusNode.className='captcha-status';statusNode.textContent='Загрузка проверки безопасности…';wrap.append(label,widget,token,statusNode);form.querySelector('.submit').before(wrap);
  const status=form.querySelector('.captcha-status');
  const tokenInput=form.elements.turnstileToken;
  const button=form.querySelector('.submit');
  let widgetId=null;
  let captchaReady=false;
  const message=(text,error=false)=>{const target=document.getElementById('message');target.replaceChildren();const box=document.createElement('div');box.className='msg'+(error?' error':'');box.textContent=String(text||'');target.appendChild(box)};
  const call=async body=>{const response=await fetch('/api/v1/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>null);if(!data||!response.ok)throw Error(data?.error||'Сервер временно недоступен');return data};
  const loadTurnstile=()=>new Promise(async(resolve,reject)=>{try{const response=await fetch('/api/v1/public/registration-config',{cache:'no-store',headers:{accept:'application/json'}});const config=await response.json().catch(()=>null);if(!response.ok||!config?.captchaConfigured||!config.turnstileSiteKey)throw Error('Cloudflare Turnstile не настроен');if(typeof window.turnstile?.render!=='function')await new Promise((ready,failed)=>{const callbackName='onLoginTurnstileLoad';const timeout=setTimeout(()=>{delete window[callbackName];failed(Error('Cloudflare API не ответил вовремя'))},15000);window[callbackName]=()=>{clearTimeout(timeout);delete window[callbackName];typeof window.turnstile?.render==='function'?ready():failed(Error('Cloudflare API загрузился некорректно'))};const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit&onload='+callbackName;script.async=true;script.onerror=()=>{clearTimeout(timeout);delete window[callbackName];failed(Error('Браузер заблокировал Cloudflare'))};document.head.appendChild(script)});resolve(config.turnstileSiteKey)}catch(error){reject(error)}});
  async function init(){button.disabled=true;try{const sitekey=await loadTurnstile();widgetId=window.turnstile.render('#login-turnstile-widget',{sitekey,theme:'dark',appearance:'always',execution:'render',size:window.matchMedia('(max-width:420px)').matches?'flexible':'normal',action:'login',retry:'auto','refresh-expired':'auto',callback:token=>{tokenInput.value=token;captchaReady=true;status.textContent='Проверка пройдена'},'expired-callback':()=>{tokenInput.value='';captchaReady=false;status.textContent='Поставьте галочку повторно'},'error-callback':code=>{tokenInput.value='';captchaReady=false;status.textContent='Ошибка Cloudflare Turnstile: '+String(code||'unknown');return true}});status.textContent='Поставьте галочку «Я не робот»';button.disabled=false}catch(error){status.textContent=error.message}}
  form.addEventListener('submit',async event=>{event.preventDefault();if(!captchaReady){status.textContent='Подтвердите, что вы не робот';return}button.disabled=true;button.textContent='Входим…';try{const result=await call(Object.fromEntries(new FormData(form)));localStorage.setItem('LF_TOKEN',result.token);location.href='/'}catch(error){message(error.message,true);button.disabled=false;button.textContent='Войти в кабинет';captchaReady=false;tokenInput.value='';if(widgetId!==null)window.turnstile?.reset(widgetId)}});
  init();
})();
