const token=localStorage.getItem('LF_TOKEN');if(!token)location.href='/auth.html';const byId=id=>document.getElementById(id);let data={design:{}},products=[];
const api=async(url,options={})=>{options.headers={...(options.headers||{}),Authorization:'Bearer '+token};const response=await fetch(url,options),body=await response.json().catch(()=>({}));if(response.status===401){localStorage.removeItem('LF_TOKEN');location.href='/auth.html';throw Error('Сессия завершена')}if(!response.ok)throw Error(body.error||`Ошибка сервера (${response.status})`);return body},esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function value(id){return byId(id).value.trim()}function productFromForm(){return{name:value('productName'),category:value('category'),price:Number(value('price'))||0,bonus:Number(value('bonus'))||0,stock:Number(value('stock'))||0,image:value('image')}}function clearForm(){for(const id of ['productName','category','price','bonus','image'])byId(id).value='';byId('stock').value='1';byId('productName').focus()}
function render(){byId('count').textContent=`(${products.length})`;byId('list').innerHTML=products.length?products.map((product,index)=>`<article class="product-row">${product.image?`<img src="${esc(product.image)}" alt="" onerror="this.hidden=true">`:'<div class="product-placeholder">▦</div>'}<div><b>${esc(product.name)}</b><div class="meta">${esc(product.category||'Без категории')} · ${Number(product.price||0).toLocaleString('ru-RU')} ₽ · +${Number(product.bonus||0)} бонусов · ${Number(product.stock||0)} шт.</div></div><div class="actions"><button type="button" class="btn" data-edit="${index}">Изменить</button><button type="button" class="btn danger" data-delete="${index}">Удалить</button></div></article>`).join(''):'<div class="empty-block"><div><b>Каталог пуст</b><span>Добавьте первый товар или импортируйте CSV.</span></div></div>'}
function addProduct(event){event.preventDefault();const product=productFromForm();if(!product.name){byId('status').textContent='Введите название товара';byId('productName').focus();return}products.push({...product,id:crypto.randomUUID()});clearForm();render();byId('status').textContent='Товар добавлен. Нажмите «Сохранить каталог».'}
function editProduct(index){const product=products[index];for(const [id,key] of [['productName','name'],['category','category'],['price','price'],['bonus','bonus'],['stock','stock'],['image','image']])byId(id).value=product[key]??'';products.splice(index,1);render();scrollTo({top:0,behavior:'smooth'})}
function parseCsvLine(line,separator){return line.split(new RegExp(separator+'(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)')).map(x=>x.trim().replace(/^\"|\"$/g,''))}function importCsv(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{const lines=String(reader.result).replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return;const separator=lines[0].includes(';')?';':',',headers=parseCsvLine(lines.shift(),separator).map(x=>x.toLowerCase());for(const line of lines){const row=parseCsvLine(line,separator),get=(...keys)=>{for(const key of keys){const index=headers.indexOf(key);if(index>=0)return row[index]||''}return''},name=get('name','название');if(name)products.push({id:crypto.randomUUID(),name,category:get('category','категория'),price:Number(get('price','цена'))||0,bonus:Number(get('bonus','бонусы'))||0,stock:Number(get('stock','остаток'))||0,image:get('image','изображение')})}render();byId('status').textContent=`Импортировано товаров: ${products.length}. Нажмите «Сохранить каталог».`;byId('csv').value=''};reader.readAsText(file)}
function downloadTemplate(){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['name,category,price,bonus,stock,image\nКапучино,Кофе,260,13,20,https://example.com/image.jpg\n'],{type:'text/csv;charset=utf-8'}));link.download='loyaltyflow-products.csv';link.click();URL.revokeObjectURL(link.href)}
async function saveCatalog(){const button=byId('saveCatalog');button.disabled=true;byId('status').textContent='Сохраняем каталог…';try{const design={...(data.design||{}),products,catalog:true};await api('/api/v1/owner/miniapp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({design})});data.design=design;byId('status').textContent='Каталог сохранён и опубликован в Mini App'}catch(error){byId('status').textContent='Ошибка: '+error.message}finally{button.disabled=false}}
byId('productForm').addEventListener('submit',addProduct);byId('saveCatalog').addEventListener('click',saveCatalog);byId('csv').addEventListener('change',event=>importCsv(event.target.files[0]));byId('downloadTemplate').addEventListener('click',downloadTemplate);byId('list').addEventListener('click',event=>{const edit=event.target.closest('[data-edit]'),remove=event.target.closest('[data-delete]');if(edit)editProduct(Number(edit.dataset.edit));if(remove){products.splice(Number(remove.dataset.delete),1);render();byId('status').textContent='Товар удалён. Сохраните каталог.'}});
(async()=>{try{data=await api('/api/v1/owner/miniapp');products=Array.isArray(data.design?.products)?data.design.products:[];render()}catch(error){byId('status').textContent='Не удалось загрузить каталог: '+error.message}})();
