(()=>{
  const registerForm=document.getElementById('registerForm');
  const verifyForm=document.getElementById('verifyForm');
  const phoneInput=document.getElementById('phoneInput');
  const status=document.querySelector('.captcha-status');
  const tokenInput=document.getElementById('turnstileToken');
  let email='';
  let phoneInstance=null;
  let captchaReady=false;
  let widgetId=null;

  const message=(text,error=false)=>{const target=document.getElementById('message');if(!target)return;target.replaceChildren();const box=document.createElement('div');box.className='msg'+(error?' error':'');box.textContent=String(text||'');target.appendChild(box)};
  const readJson=async(response,fallback)=>{const data=await response.json().catch(()=>null);if(!data||typeof data!=='object'||!response.ok)throw Error(data?.error||fallback);return data};
  const call=async(url,body)=>readJson(await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),'Сервер временно недоступен. Попробуйте позже.');
  const fieldOf=input=>input?.closest('.field');
  const clearErrors=form=>{form.querySelectorAll('.field').forEach(field=>{field.classList.remove('invalid');field.querySelector('.field-error')?.remove()});form.querySelector('.captcha-error')?.remove()};
  const errorFor=(input,text)=>{const field=fieldOf(input);if(!field)return;field.classList.add('invalid');let error=field.querySelector('.field-error');if(!error){error=document.createElement('span');error.className='field-error';field.append(error)}error.textContent=text};
  const validate=form=>{clearErrors(form);let ok=true;for(const input of form.querySelectorAll('input[required]')){const value=input.value.trim();let text='';if(!value)text='Заполните поле';else if(input.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))text='Введите корректный email';else if(input.name==='age'&&(!/^\d{1,3}$/.test(value)||Number(value)<14||Number(value)>100))text='Укажите возраст от 14 до 100';else if(input.name==='password'&&!/^(?=.*[A-Za-zА-Яа-я])(?=.*\d)(?=.*[#@]).{8,}$/.test(value))text='Минимум 8 символов, буква, цифра и # или @';else if(input.name==='code'&&!/^\d{6}$/.test(value))text='Введите шестизначный код';if(text){errorFor(input,text);ok=false}}form.querySelector('.invalid input')?.focus();return ok};

  function detectedCountry(){const locale=(navigator.languages?.[0]||navigator.language||'').replace('_','-'),parts=locale.split('-'),region=parts[1]?.toLowerCase();if(region?.length===2)return region;const language=parts[0].toLowerCase(),fallback={ru:'ru',en:'us',de:'de',fr:'fr',es:'es',it:'it',pt:'br',tr:'tr',uk:'ua',kk:'kz',uz:'uz',zh:'cn',ja:'jp',ko:'kr'}[language];if(fallback)return fallback;return Intl.DateTimeFormat().resolvedOptions().timeZone==='Asia/Yekaterinburg'?'ru':'us'}
  async function initPhone(){if(!phoneInput||!window.intlTelInput)return;phoneInstance=window.intlTelInput(phoneInput,{initialCountry:detectedCountry(),nationalMode:false,formatAsYouType:true,autoPlaceholder:'aggressive',countrySearch:true,loadUtils:()=>import('https:'+'//cdn.jsdelivr.net/npm/intl-tel-input@29.2.3/dist/js/utils.js')});await phoneInstance.promise.catch(()=>{});const country=phoneInstance.getSelectedCountryData();if(!phoneInput.value&&country?.dialCode)phoneInstance.setNumber('+'+country.dialCode)}
  const loadTurnstile=()=>new Promise((resolve,reject)=>{if(typeof window.turnstile?.render==='function')return resolve();const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.onload=()=>{let checks=0;const wait=()=>typeof window.turnstile?.render==='function'?resolve():checks++<100?setTimeout(wait,50):reject(Error('Cloudflare API не запустился'));wait()};script.onerror=()=>reject(Error('Браузер заблокировал загрузку Cloudflare'));document.head.appendChild(script)});
  async function initCaptcha(){const button=registerForm.querySelector('.submit');button.disabled=true;try{const config=await readJson(await fetch('/api/v1/public/registration-config',{cache:'no-store',headers:{accept:'application/json'}}),'Не удалось получить настройки проверки');if(!config.captchaConfigured||!config.turnstileSiteKey)throw Error('Cloudflare Turnstile не настроен на сервере');await loadTurnstile();widgetId=window.turnstile.render('#turnstile',{sitekey:config.turnstileSiteKey,theme:'dark',appearance:'always',execution:'render',size:'normal',action:'register',retry:'auto','refresh-expired':'auto',callback:token=>{tokenInput.value=token;captchaReady=true;status.textContent='Проверка пройдена'},'expired-callback':()=>{tokenInput.value='';captchaReady=false;status.textContent='Поставьте галочку повторно'},'error-callback':code=>{tokenInput.value='';captchaReady=false;status.textContent='Ошибка Cloudflare Turnstile: '+String(code||'unknown');console.error('Turnstile',code);return true}});status.textContent='Поставьте галочку «Я не робот»';button.disabled=false}catch(error){status.textContent=error.message;button.disabled=true;console.error(error)}}

  document.querySelectorAll('form').forEach(form=>form.noValidate=true);
  document.addEventListener('input',event=>{const field=fieldOf(event.target);if(field){field.classList.remove('invalid');field.querySelector('.field-error')?.remove()}});
  registerForm.addEventListener('submit',async event=>{event.preventDefault();let valid=validate(registerForm);if(phoneInstance){await phoneInstance.promise.catch(()=>{});if(!phoneInstance.isValidNumber()){errorFor(phoneInput,'Проверьте код страны и номер телефона');valid=false}}if(!captchaReady){let error=registerForm.querySelector('.captcha-error');if(!error){error=document.createElement('div');error.className='captcha-error';registerForm.querySelector('.captcha-wrap')?.append(error)}error.textContent='Подтвердите, что вы не робот';valid=false}if(!valid)return;const button=registerForm.querySelector('.submit');button.disabled=true;button.textContent='Отправляем код…';const data=Object.fromEntries(new FormData(registerForm));if(phoneInstance)data.phone=phoneInstance.getNumber();try{const result=await call('/api/v1/auth/register',data);email=data.email;registerForm.closest('.register-box').classList.add('hidden');document.querySelector('.verify-box').classList.add('active');document.getElementById('verifyEmail').textContent=email;message(result.message);document.querySelector('#verifyForm input').focus()}catch(error){message(error.message,true);button.disabled=false;button.textContent='Создать аккаунт';if(widgetId!==null)window.turnstile?.reset(widgetId);captchaReady=false;tokenInput.value=''}});
  verifyForm.addEventListener('submit',async event=>{event.preventDefault();if(!validate(verifyForm))return;const button=verifyForm.querySelector('.submit');button.disabled=true;button.textContent='Проверяем код…';try{const result=await call('/api/v1/auth/verify',{email,code:new FormData(verifyForm).get('code')});message(result.message);setTimeout(()=>location.href='/login.html',900)}catch(error){message(error.message,true);button.disabled=false;button.textContent='Подтвердить email'}});

  initPhone();
  initCaptcha();
})();
