import express from 'express';
import pg from 'pg';
import rateLimit from 'express-rate-limit';
import {verifySession} from './security.js';
const {Pool}=pg,pool=new Pool({connectionString:process.env.DATABASE_URL}),secret=String(process.env.JWT_SECRET||''),allowedOrigin=(()=>{try{return new URL(process.env.PUBLIC_APP_URL).origin}catch{return''}})(),originalListen=express.application.listen;let schemaReady=false;
async function schema(){if(schemaReady)return;await pool.query(`create table if not exists loyalty_cashier_operations(id uuid primary key default gen_random_uuid(),owner_id uuid not null references users(id) on delete cascade,customer_id uuid not null references loyalty_customers(id) on delete cascade,request_id uuid not null,bonus_amount integer not null check(bonus_amount>0),order_total numeric(14,2) not null default 0,result jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(owner_id,request_id))`);schemaReady=true}
function cookie(req){const raw=String(req.headers.cookie||'');for(const name of['__Host-lf_session','lf_session']){const match=raw.match(new RegExp('(?:^|;\\s*)'+name+'=([^;]+)'));if(match)try{return decodeURIComponent(match[1])}catch{return''}}return''}
async function auth(req,res,next){try{const header=String(req.get('Authorization')||''),token=/^Bearer\s+/i.test(header)&&!/^Bearer\s+cookie-session$/i.test(header)?header.replace(/^Bearer\s+/i,'').trim():cookie(req),session=verifySession(token,secret);if(!session)return res.status(401).json({error:'Войдите в кабинет'});const user=(await pool.query('select id,status,trial_end,session_version from users where id=$1',[session.id])).rows[0];if(!user||Number(session.sv||0)!==Number(user.session_version||0))return res.status(401).json({error:'Сессия отозвана'});if(['pending_admin','email_pending','blocked','disabled','rejected','frozen'].includes(String(user.status||'').toLowerCase()))return res.status(403).json({error:'Аккаунт недоступен'});if(user.trial_end&&new Date(user.trial_end).getTime()<Date.now())return res.status(403).json({error:'Срок доступа истёк'});if(!['GET','HEAD','OPTIONS'].includes(req.method)){const origin=String(req.get('Origin')||'');if(origin&&allowedOrigin&&origin!==allowedOrigin)return res.status(403).json({error:'Запрос отклонён проверкой источника'})}req.cashierOwner=user;res.setHeader('Cache-Control','no-store');next()}catch(error){console.error('Cashier auth failed',error);res.status(503).json({error:'Не удалось проверить доступ'})}}
const scanLimit=rateLimit({windowMs:60*1000,limit:90,standardHeaders:true,legacyHeaders:false,keyGenerator:req=>String(req.cashierOwner?.id||req.ip),message:{error:'Слишком много сканирований'}}),redeemLimit=rateLimit({windowMs:60*1000,limit:30,standardHeaders:true,legacyHeaders:false,keyGenerator:req=>String(req.cashierOwner?.id||req.ip),message:{error:'Слишком много операций списания'}});
function parseQr(value){const match=String(value||'').trim().match(/^loyaltyflow:v2:([0-9a-f-]{36}):([0-9a-f-]{36}):(\d{1,10})$/i);return match?{tenant:match[1].toLowerCase(),customerId:match[2].toLowerCase(),snapshot:Math.max(0,Number(match[3])||0)}:null}
const publicCustomer=row=>({id:row.id,name:[row.first_name,row.last_name].filter(Boolean).join(' ')||row.username||'Клиент',username:row.username||'',phone:row.phone||'',balance:Number(row.balance)||0,blocked:Boolean(row.blocked),updatedAt:row.updated_at});
async function lookup(req,res){try{const qr=parseQr(req.query.qr);if(!qr)return res.status(400).json({error:'QR не распознан. Откройте актуальный QR клиента в боте.'});if(qr.tenant!==String(req.cashierOwner.id).toLowerCase())return res.status(403).json({error:'QR относится к другой программе лояльности'});const row=(await pool.query('select id,first_name,last_name,username,phone,balance,blocked,updated_at from loyalty_customers where id=$1 and owner_id=$2',[qr.customerId,req.cashierOwner.id])).rows[0];if(!row)return res.status(404).json({error:'Клиент не найден'});if(row.blocked)return res.status(403).json({error:'Клиент заблокирован'});res.json({ok:true,customer:publicCustomer(row),qrSnapshotBalance:qr.snapshot,balanceChanged:Number(row.balance)!==qr.snapshot})}catch(error){console.error('Cashier lookup failed',error);res.status(500).json({error:'Не удалось проверить QR'})}}
async function redeem(req,res){const db=await pool.connect();try{const qr=parseQr(req.body?.qr),amount=Math.trunc(Number(req.body?.amount)||0),orderTotal=Math.max(0,Math.min(1e9,Number(req.body?.orderTotal)||0)),requestId=String(req.body?.requestId||'');if(!qr)return res.status(400).json({error:'Некорректный QR клиента'});if(qr.tenant!==String(req.cashierOwner.id).toLowerCase())return res.status(403).json({error:'QR относится к другой программе'});if(!/^[0-9a-f-]{36}$/i.test(requestId))return res.status(400).json({error:'Некорректный идентификатор операции'});if(amount<1||amount>1000000)return res.status(400).json({error:'Сумма списания должна быть от 1 до 1 000 000 бонусов'});await schema();await db.query('begin');const duplicate=(await db.query('select result from loyalty_cashier_operations where owner_id=$1 and request_id=$2',[req.cashierOwner.id,requestId])).rows[0];if(duplicate){await db.query('commit');return res.json({...duplicate.result,idempotent:true})}const customer=(await db.query('select * from loyalty_customers where id=$1 and owner_id=$2 for update',[qr.customerId,req.cashierOwner.id])).rows[0];if(!customer){await db.query('rollback');return res.status(404).json({error:'Клиент не найден'})}if(customer.blocked){await db.query('rollback');return res.status(403).json({error:'Клиент заблокирован'})}if(Number(customer.balance)<amount){await db.query('rollback');return res.status(409).json({error:'Недостаточно бонусов. Доступно: '+Number(customer.balance)})}const updated=(await db.query('update loyalty_customers set balance=balance-$1,updated_at=now() where id=$2 returning *',[amount,customer.id])).rows[0];await db.query(`insert into loyalty_transactions(owner_id,bot_key,customer_id,kind,bonus_delta,order_total,description,meta) values($1,$2,$3,'debit',$4,$5,'Списание бонусов на кассе',$6::jsonb)`,[req.cashierOwner.id,customer.bot_key,customer.id,-amount,orderTotal,JSON.stringify({source:'cashier',requestId,qrSnapshotBalance:qr.snapshot})]);const result={ok:true,customer:publicCustomer(updated),redeemed:amount,orderTotal};await db.query('insert into loyalty_cashier_operations(owner_id,customer_id,request_id,bonus_amount,order_total,result) values($1,$2,$3,$4,$5,$6::jsonb)',[req.cashierOwner.id,customer.id,requestId,amount,orderTotal,JSON.stringify(result)]);await db.query('commit');res.json(result)}catch(error){try{await db.query('rollback')}catch{}console.error('Cashier redeem failed',error);res.status(500).json({error:'Не удалось списать бонусы'})}finally{db.release()}}
express.application.listen=function(...args){if(!this.__cashierInstalled){this.__cashierInstalled=true;this.get('/api/v1/owner/cashier/customer',auth,scanLimit,lookup);this.post('/api/v1/owner/cashier/redeem',auth,redeemLimit,express.json({limit:'12kb'}),redeem)}return originalListen.apply(this,args)};
