import express from 'express';
import pg from 'pg';
import rateLimit from 'express-rate-limit';
import {verifySession,encryptSecret,decryptSecret} from './security.js';
const {Pool}=pg,pool=new Pool({connectionString:process.env.DATABASE_URL}),jwtSecret=String(process.env.JWT_SECRET||''),publicOrigin=(()=>{try{return new URL(process.env.PUBLIC_APP_URL).origin}catch{return''}})(),originalListen=express.application.listen;let schemaReady=false;
async function ensureSchema(){if(schemaReady)return;await pool.query(`create table if not exists owner_integrations(owner_id uuid not null references users(id) on delete cascade,provider text not null,secret_enc text not null,meta jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(owner_id,provider))`);schemaReady=true}
function cookieToken(req){const value=String(req.headers.cookie||'');for(const name of['__Host-lf_session','lf_session']){const match=value.match(new RegExp('(?:^|;\\s*)'+name+'=([^;]+)'));if(match)try{return decodeURIComponent(match[1])}catch{return''}}return''}
async function ownerAuth(req,res,next){try{const header=String(req.get('Authorization')||''),token=/^Bearer\s+/i.test(header)&&!/^Bearer\s+cookie-session$/i.test(header)?header.replace(/^Bearer\s+/i,'').trim():cookieToken(req),session=verifySession(token,jwtSecret);if(!session)return res.status(401).json({error:'Войдите в аккаунт'});const user=(await pool.query('select id,email,status,trial_end,session_version from users where id=$1',[session.id])).rows[0];if(!user||Number(session.sv||0)!==Number(user.session_version||0))return res.status(401).json({error:'Сессия отозвана. Войдите снова.'});if(['pending_admin','email_pending','blocked','disabled','rejected','frozen'].includes(String(user.status||'').toLowerCase()))return res.status(403).json({error:'Аккаунт недоступен'});if(user.trial_end&&new Date(user.trial_end).getTime()<Date.now())return res.status(403).json({error:'Срок доступа истёк'});if(!['GET','HEAD','OPTIONS'].includes(req.method)){const origin=String(req.get('Origin')||'');if(origin&&publicOrigin&&origin!==publicOrigin)return res.status(403).json({error:'Запрос отклонён проверкой источника'})}req.integrationOwner=user;res.setHeader('Cache-Control','no-store');next()}catch(error){console.error('Integration authorization failed',error);res.status(503).json({error:'Не удалось проверить сессию'})}}
const connectLimit=rateLimit({windowMs:15*60*1000,limit:10,standardHeaders:true,legacyHeaders:false,keyGenerator:req=>String(req.integrationOwner?.id||req.ip),message:{error:'Слишком много попыток подключения. Попробуйте позже.'}});function validToken(value){return typeof value==='string'&&value.length>=20&&value.length<=512&&!/[\s\x00-\x1f\x7f]/.test(value)}
async function upstreamError(response,token){let message='HTTP '+response.status;try{const raw=(await response.text()).slice(0,12000),data=JSON.parse(raw),entry=Array.isArray(data?.errors)?data.errors[0]:data;message=String(entry?.error||entry?.message||entry?.error_message||message)}catch{}return message.replaceAll(token,'[скрыто]').replace(/[\x00-\x1f\x7f]+/g,' ').slice(0,300)}
async function moyskladRequest(token,path,label){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),9000);try{const base='https:'+'//api.moysklad.ru/api/remap/1.2/',response=await fetch(base+path,{headers:{Authorization:'Bearer '+token,Accept:'application/json','Accept-Encoding':'gzip','User-Agent':'LoyaltyFlow/1.0'},signal:controller.signal,redirect:'error'});if(!response.ok){const detail=await upstreamError(response,token);if(response.status===401||response.status===403)throw Object.assign(Error('МойСклад отклонил токен или права доступа: '+detail),{status:400});throw Object.assign(Error((label||'МойСклад')+': '+detail),{status:response.status===400?400:502})}const length=Number(response.headers.get('content-length')||0);if(length>2000000)throw Object.assign(Error('Ответ МойСклад слишком большой'),{status:502});return await response.json()}catch(error){if(error.name==='AbortError')throw Object.assign(Error('МойСклад не ответил за 9 секунд'),{status:504});throw error}finally{clearTimeout(timer)}}
async function inspectAccount(token){const employee=await moyskladRequest(token,'context/employee','Проверка токена');let storesResult={rows:[]},storesWarning='';try{storesResult=await moyskladRequest(token,'entity/retailstore?limit=100','Загрузка точек продаж')}catch(error){storesWarning=String(error.message||'Не удалось загрузить точки продаж').slice(0,300)}const stores=(Array.isArray(storesResult?.rows)?storesResult.rows:[]).map(store=>({id:String(store.id||'').slice(0,80),name:String(store.name||'Точка продаж').slice(0,160),active:store.archived!==true,address:String(store.addressFull||store.address||'').slice(0,300)}));return{accountName:String(employee?.name||employee?.fullName||'МойСклад').slice(0,160),employeeEmail:String(employee?.email||'').slice(0,254),stores,storesWarning,checkedAt:new Date().toISOString()}}
async function status(req,res){try{await ensureSchema();const row=(await pool.query("select meta,updated_at from owner_integrations where owner_id=$1 and provider='moysklad'",[req.integrationOwner.id])).rows[0];res.json({provider:'moysklad',connected:Boolean(row),meta:row?.meta||{},updatedAt:row?.updated_at||null})}catch(error){console.error('Integration status failed',error);res.status(500).json({error:'Не удалось загрузить состояние интеграции'})}}
async function connect(req,res){try{const token=String(req.body?.token||'').trim();if(!validToken(token))return res.status(400).json({error:'Введите корректный токен МойСклад'});await ensureSchema();const meta=await inspectAccount(token),secret=encryptSecret(token,jwtSecret);await pool.query("insert into owner_integrations(owner_id,provider,secret_enc,meta) values($1,'moysklad',$2,$3::jsonb) on conflict(owner_id,provider) do update set secret_enc=excluded.secret_enc,meta=excluded.meta,updated_at=now()",[req.integrationOwner.id,secret,JSON.stringify(meta)]);res.json({ok:true,connected:true,meta})}catch(error){console.error('MoySklad connect failed',{status:error.status,message:error.message});res.status(Number(error.status)||500).json({error:error.message||'Не удалось подключить МойСклад'})}}
async function test(req,res){try{await ensureSchema();const row=(await pool.query("select secret_enc from owner_integrations where owner_id=$1 and provider='moysklad'",[req.integrationOwner.id])).rows[0];if(!row)return res.status(404).json({error:'Сначала подключите МойСклад'});const token=decryptSecret(row.secret_enc,jwtSecret),meta=await inspectAccount(token);await pool.query("update owner_integrations set meta=$1::jsonb,updated_at=now() where owner_id=$2 and provider='moysklad'",[JSON.stringify(meta),req.integrationOwner.id]);res.json({ok:true,connected:true,meta})}catch(error){console.error('MoySklad test failed',{status:error.status,message:error.message});res.status(Number(error.status)||500).json({error:error.message||'Не удалось проверить МойСклад'})}}
async function disconnect(req,res){try{await ensureSchema();await pool.query("delete from owner_integrations where owner_id=$1 and provider='moysklad'",[req.integrationOwner.id]);res.json({ok:true,connected:false})}catch(error){console.error('MoySklad disconnect failed',error);res.status(500).json({error:'Не удалось отключить МойСклад'})}}
express.application.listen=function(...args){if(!this.__ownerIntegrationsInstalled){this.__ownerIntegrationsInstalled=true;this.get('/api/v1/owner/integrations/moysklad',ownerAuth,status);this.post('/api/v1/owner/integrations/moysklad/connect',ownerAuth,connectLimit,express.json({limit:'16kb'}),connect);this.post('/api/v1/owner/integrations/moysklad/test',ownerAuth,connectLimit,test);this.post('/api/v1/owner/integrations/moysklad/disconnect',ownerAuth,disconnect)}return originalListen.apply(this,args)};
