import express from 'express';
import pg from 'pg';
import rateLimit from 'express-rate-limit';
import {verifySession,encryptSecret,decryptSecret} from './security.js';
const {Pool}=pg,pool=new Pool({connectionString:process.env.DATABASE_URL}),jwtSecret=String(process.env.JWT_SECRET||''),publicOrigin=(()=>{try{return new URL(process.env.PUBLIC_APP_URL).origin}catch{return''}})(),originalListen=express.application.listen;let schemaReady=false;
async function ensureSchema(){if(schemaReady)return;await pool.query(`create table if not exists owner_integrations(owner_id uuid not null references users(id) on delete cascade,provider text not null,secret_enc text not null,meta jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(owner_id,provider))`);schemaReady=true}
function cookieToken(req){const value=String(req.headers.cookie||'');for(const name of['__Host-lf_session','lf_session']){const match=value.match(new RegExp('(?:^|;\\s*)'+name+'=([^;]+)'));if(match)try{return decodeURIComponent(match[1])}catch{return''}}return''}
async function ownerAuth(req,res,next){try{const header=String(req.get('Authorization')||''),token=/^Bearer\s+/i.test(header)&&!/^Bearer\s+cookie-session$/i.test(header)?header.replace(/^Bearer\s+/i,'').trim():cookieToken(req),session=verifySession(token,jwtSecret);if(!session)return res.status(401).json({error:'Войдите в аккаунт'});const user=(await pool.query('select id,email,status,trial_end,session_version,admin_frozen from users where id=$1',[session.id])).rows[0];if(!user||Number(session.sv||0)!==Number(user.session_version||0))return res.status(401).json({error:'Сессия отозвана. Войдите снова.'});if(user.admin_frozen||['pending_admin','email_pending','blocked','disabled','rejected','frozen'].includes(String(user.status||'').toLowerCase()))return res.status(403).json({error:'Аккаунт недоступен'});if(user.trial_end&&new Date(user.trial_end).getTime()<Date.now())return res.status(403).json({error:'Срок доступа истёк'});if(!['GET','HEAD','OPTIONS'].includes(req.method)){const origin=String(req.get('Origin')||'');if(origin&&publicOrigin&&origin!==publicOrigin)return res.status(403).json({error:'Запрос отклонён проверкой источника'})}req.integrationOwner=user;res.setHeader('Cache-Control','no-store');next()}catch(error){console.error('Integration authorization failed',error);res.status(503).json({error:'Не удалось проверить сессию'})}}
const connectLimit=rateLimit({windowMs:15*60*1000,limit:10,standardHeaders:true,legacyHeaders:false,keyGenerator:req=>String(req.integrationOwner?.id||req.ip),message:{error:'Слишком много попыток подключения. Попробуйте позже.'}});function validToken(value){return typeof value==='string'&&value.length>=20&&value.length<=512&&!/[\s\x00-\x1f\x7f]/.test(value)}
async function upstreamError(response,token){let message='HTTP '+response.status;try{const raw=(await response.text()).slice(0,12000),data=JSON.parse(raw),entry=Array.isArray(data?.errors)?data.errors[0]:data;message=String(entry?.error||entry?.message||entry?.error_message||message)}catch{}return message.replaceAll(token,'[скрыто]').replace(/[\x00-\x1f\x7f]+/g,' ').slice(0,300)}
async function moyskladRequest(token,path,label){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),9000);try{const base='https:'+'//api.moysklad.ru/api/remap/1.2/',response=await fetch(base+path,{headers:{Authorization:'Bearer '+token,Accept:'application/json;charset=utf-8','Accept-Encoding':'gzip','User-Agent':'LoyaltyFlow/1.0'},signal:controller.signal,redirect:'error'});if(!response.ok){const detail=await upstreamError(response,token);if(response.status===401||response.status===403)throw Object.assign(Error('МойСклад отклонил токен или права доступа: '+detail),{status:400});throw Object.assign(Error((label||'МойСклад')+': '+detail),{status:response.status===400?400:502})}const length=Number(response.headers.get('content-length')||0);if(length>2000000)throw Object.assign(Error('Ответ МойСклад слишком большой'),{status:502});return await response.json()}catch(error){if(error.name==='AbortError')throw Object.assign(Error('МойСклад не ответил за 9 секунд'),{status:504});throw error}finally{clearTimeout(timer)}}
async function inspectAccount(token){const employee=await moyskladRequest(token,'context/employee','Проверка токена');let storesResult={rows:[]},storesWarning='';try{storesResult=await moyskladRequest(token,'entity/retailstore?limit=100','Загрузка точек продаж')}catch(error){storesWarning=String(error.message||'Не удалось загрузить точки продаж').slice(0,300)}const stores=(Array.isArray(storesResult?.rows)?storesResult.rows:[]).map(store=>({id:String(store.id||'').slice(0,80),name:String(store.name||'Точка продаж').slice(0,160),active:store.archived!==true,address:String(store.addressFull||store.address||'').slice(0,300)}));return{accountName:String(employee?.name||employee?.fullName||'МойСклад').slice(0,160),employeeEmail:String(employee?.email||'').slice(0,254),stores,storesWarning,checkedAt:new Date().toISOString()}}
async function status(req,res){try{await ensureSchema();const row=(await pool.query("select meta,updated_at from owner_integrations where owner_id=$1 and provider='moysklad'",[req.integrationOwner.id])).rows[0];res.json({provider:'moysklad',connected:Boolean(row),meta:row?.meta||{},updatedAt:row?.updated_at||null})}catch(error){console.error('Integration status failed',error);res.status(500).json({error:'Не удалось загрузить состояние интеграции'})}}
async function connect(req,res){try{const token=String(req.body?.token||'').trim();if(!validToken(token))return res.status(400).json({error:'Введите корректный токен МойСклад'});await ensureSchema();const meta=await inspectAccount(token),secret=encryptSecret(token,jwtSecret);await pool.query("insert into owner_integrations(owner_id,provider,secret_enc,meta) values($1,'moysklad',$2,$3::jsonb) on conflict(owner_id,provider) do update set secret_enc=excluded.secret_enc,meta=excluded.meta,updated_at=now()",[req.integrationOwner.id,secret,JSON.stringify(meta)]);res.json({ok:true,connected:true,meta})}catch(error){console.error('MoySklad connect failed',{status:error.status,message:error.message});res.status(Number(error.status)||500).json({error:error.message||'Не удалось подключить МойСклад'})}}
async function test(req,res){try{await ensureSchema();const row=(await pool.query("select secret_enc from owner_integrations where owner_id=$1 and provider='moysklad'",[req.integrationOwner.id])).rows[0];if(!row)return res.status(404).json({error:'Сначала подключите МойСклад'});const token=decryptSecret(row.secret_enc,jwtSecret),meta=await inspectAccount(token);await pool.query("update owner_integrations set meta=$1::jsonb,updated_at=now() where owner_id=$2 and provider='moysklad'",[JSON.stringify(meta),req.integrationOwner.id]);res.json({ok:true,connected:true,meta})}catch(error){console.error('MoySklad test failed',{status:error.status,message:error.message});res.status(Number(error.status)||500).json({error:error.message||'Не удалось проверить МойСклад'})}}
async function disconnect(req,res){try{await ensureSchema();await pool.query("delete from owner_integrations where owner_id=$1 and provider='moysklad'",[req.integrationOwner.id]);res.json({ok:true,connected:false})}catch(error){console.error('MoySklad disconnect failed',error);res.status(500).json({error:'Не удалось отключить МойСклад'})}}
express.application.listen=function(...args){if(!this.__ownerIntegrationsInstalled){this.__ownerIntegrationsInstalled=true;this.get('/api/v1/owner/integrations/moysklad',ownerAuth,status);this.post('/api/v1/owner/integrations/moysklad/connect',ownerAuth,connectLimit,express.json({limit:'16kb'}),connect);this.post('/api/v1/owner/integrations/moysklad/test',ownerAuth,connectLimit,test);this.post('/api/v1/owner/integrations/moysklad/disconnect',ownerAuth,disconnect)}return originalListen.apply(this,args)};


/* Эвотор: безопасная серверная синхронизация товаров и остатков. */
const evotorBase='https://api.evotor.ru/';
const evotorInterval=Math.max(300000,Number(process.env.EVOTOR_SYNC_INTERVAL_MS||900000));
function safeEvotorId(value){const id=String(value||'').trim();return /^[0-9a-fA-F-]{8,80}$/.test(id)?id:''}
async function evotorRequest(token,path,label){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const clean=String(path||'').replace(/^\/+/,''),url=new URL(clean,evotorBase);if(url.origin!==new URL(evotorBase).origin)throw Object.assign(Error('Недопустимый адрес Эвотора'),{status:400});const response=await fetch(url,{headers:{Authorization:'Bearer '+token,Accept:'Application/vnd.evotor.v2+json','User-Agent':'LoyaltyFlow/1.0'},signal:controller.signal,redirect:'error'});if(!response.ok){const detail=await upstreamError(response,token);if(response.status===401||response.status===403)throw Object.assign(Error('Эвотор отклонил токен или права доступа: '+detail),{status:400});throw Object.assign(Error((label||'Эвотор')+': '+detail),{status:response.status===400?400:502})}const length=Number(response.headers.get('content-length')||0);if(length>4000000)throw Object.assign(Error('Ответ Эвотора слишком большой'),{status:502});return await response.json()}catch(error){if(error.name==='AbortError')throw Object.assign(Error('Эвотор не ответил за 10 секунд'),{status:504});throw error}finally{clearTimeout(timer)}}
async function evotorCollection(token,path,label,maxPages=5){const items=[];let cursor='';for(let page=0;page<maxPages;page++){const suffix=cursor?(path.includes('?')?'&':'?')+'cursor='+encodeURIComponent(cursor):'';const data=await evotorRequest(token,path+suffix,label),batch=Array.isArray(data)?data:Array.isArray(data?.items)?data.items:[];items.push(...batch);const next=String(data?.paging?.next_cursor||'');if(!next||!batch.length)break;cursor=next}return items}
function evotorStoreView(store,devicesCount=0){return{id:String(store?.id||store?.uuid||'').slice(0,80),name:String(store?.name||'Магазин Эвотор').slice(0,160),address:String(store?.address||store?.address_full||store?.addressFull||'').slice(0,300),devicesCount}}
async function inspectEvotor(token){const stores=await evotorCollection(token,'stores?limit=100','Загрузка магазинов Эвотор',3),views=[];for(const store of stores.slice(0,25)){const storeId=safeEvotorId(store?.id||store?.uuid);let devicesCount=0;if(storeId){try{devicesCount=(await evotorCollection(token,'stores/'+encodeURIComponent(storeId)+'/devices?limit=100','Загрузка касс',2)).length}catch{devicesCount=0}}views.push(evotorStoreView(store,devicesCount))}return{accountName:'Эвотор',stores:views,checkedAt:new Date().toISOString()}}
function evotorProductView(product,storeId){const sourceId=String(product?.id||product?.uuid||'').trim().slice(0,120),name=String(product?.name||product?.short_name||product?.shortName||'').trim().slice(0,160);if(!sourceId||!name)return null;const rawPrice=Number(product?.price),rawStock=Number(product?.quantity??product?.stock??0),image=String(product?.image||'').trim();return{ id:'evotor-'+sourceId,name,category:String(product?.group_name||product?.groupName||product?.product_group_name||'Эвотор').slice(0,100),price:Number.isFinite(rawPrice)&&rawPrice>=0?rawPrice:0,bonus:0,stock:Number.isFinite(rawStock)&&rawStock>=0?Math.floor(rawStock):0,image:/^https:\/\//i.test(image)?image.slice(0,1000):'',description:String(product?.description||'').slice(0,2000),source:'evotor',evotorId:sourceId,evotorStoreId:storeId}}
async function syncEvotor(ownerId,token,baseMeta={}){const stores=await evotorCollection(token,'stores?limit=100','Загрузка магазинов Эвотор',3),allProducts=[],warnings=[],views=[];let documentsCount=0,productsLoadFailed=false;for(const store of stores.slice(0,25)){const storeId=safeEvotorId(store?.id||store?.uuid);if(!storeId)continue;let devicesCount=0;try{const devices=await evotorCollection(token,'stores/'+encodeURIComponent(storeId)+'/devices?limit=100','Загрузка касс',2);devicesCount=devices.length}catch(error){warnings.push('Не удалось загрузить кассы одного из магазинов')}try{const products=await evotorCollection(token,'stores/'+encodeURIComponent(storeId)+'/products?limit=200','Загрузка товаров',10);for(const product of products.slice(0,2000)){const view=evotorProductView(product,storeId);if(view)allProducts.push(view)}}catch(error){productsLoadFailed=true;warnings.push('Нет права product:read или не удалось загрузить товары')}try{const documents=await evotorCollection(token,'stores/'+encodeURIComponent(storeId)+'/documents?limit=100','Проверка документов',2);documentsCount+=documents.length}catch{warnings.push('Нет права document:read — чеки не проверены')}views.push(evotorStoreView(store,devicesCount))}const user=(await pool.query('select miniapp_design from users where id=$1',[ownerId])).rows[0],design=user?.miniapp_design&&typeof user.miniapp_design==='object'?user.miniapp_design:{},existing=Array.isArray(design.products)?design.products:[],manual=existing.filter(item=>item?.source!=='evotor'&&!item?.evotorId),previousEvotor=existing.filter(item=>item?.source==='evotor'||item?.evotorId),syncedProducts=productsLoadFailed?previousEvotor:allProducts,nextDesign={...design,products:[...manual,...syncedProducts],catalog:true};await pool.query("update users set miniapp_design=$1::jsonb,miniapp_updated_at=now() where id=$2",[JSON.stringify(nextDesign),ownerId]);const meta={...baseMeta,accountName:'Эвотор',stores:views,productsCount:syncedProducts.length,documentsCount,syncedAt:new Date().toISOString(),syncWarning:[...new Set(warnings)].slice(0,3).join('. ')||''};await pool.query("update owner_integrations set meta=$1::jsonb,updated_at=now() where owner_id=$2 and provider='evotor'",[JSON.stringify(meta),ownerId]);return meta}
async function evotorStatus(req,res){try{await ensureSchema();const row=(await pool.query("select meta,updated_at from owner_integrations where owner_id=$1 and provider='evotor'",[req.integrationOwner.id])).rows[0];res.json({provider:'evotor',connected:Boolean(row),meta:row?.meta||{},updatedAt:row?.updated_at||null})}catch(error){console.error('Evotor status failed',error);res.status(500).json({error:'Не удалось загрузить состояние Эвотора'})}}
async function evotorConnect(req,res){try{const token=String(req.body?.token||'').trim();if(!validToken(token)||token.length>4096)return res.status(400).json({error:'Введите корректный токен доступа Эвотор'});await ensureSchema();const meta=await inspectEvotor(token),secret=encryptSecret(token,jwtSecret);await pool.query("insert into owner_integrations(owner_id,provider,secret_enc,meta) values($1,'evotor',$2,$3::jsonb) on conflict(owner_id,provider) do update set secret_enc=excluded.secret_enc,meta=excluded.meta,updated_at=now()",[req.integrationOwner.id,secret,JSON.stringify(meta)]);let synced=meta;try{synced=await syncEvotor(req.integrationOwner.id,token,meta)}catch(error){console.error('Evotor initial sync failed',{status:error.status,message:error.message});synced={...meta,syncWarning:'Подключено, но синхронизация товаров не выполнена. Проверьте права product:read.'};await pool.query("update owner_integrations set meta=$1::jsonb,updated_at=now() where owner_id=$2 and provider='evotor'",[JSON.stringify(synced),req.integrationOwner.id])}res.json({ok:true,connected:true,meta:synced})}catch(error){console.error('Evotor connect failed',{status:error.status,message:error.message});res.status(Number(error.status)||500).json({error:error.message||'Не удалось подключить Эвотор'})}}
async function evotorTest(req,res){try{await ensureSchema();const row=(await pool.query("select secret_enc,meta from owner_integrations where owner_id=$1 and provider='evotor'",[req.integrationOwner.id])).rows[0];if(!row)return res.status(404).json({error:'Сначала подключите Эвотор'});const token=decryptSecret(row.secret_enc,jwtSecret),meta=await inspectEvotor(token);await pool.query("update owner_integrations set meta=$1::jsonb,updated_at=now() where owner_id=$2 and provider='evotor'",[JSON.stringify(meta),req.integrationOwner.id]);res.json({ok:true,connected:true,meta})}catch(error){console.error('Evotor test failed',{status:error.status,message:error.message});res.status(Number(error.status)||500).json({error:error.message||'Не удалось проверить Эвотор'})}}
async function evotorSync(req,res){try{await ensureSchema();const row=(await pool.query("select secret_enc,meta from owner_integrations where owner_id=$1 and provider='evotor'",[req.integrationOwner.id])).rows[0];if(!row)return res.status(404).json({error:'Сначала подключите Эвотор'});const token=decryptSecret(row.secret_enc,jwtSecret),meta=await syncEvotor(req.integrationOwner.id,token,row.meta||{});res.json({ok:true,connected:true,meta})}catch(error){console.error('Evotor sync failed',{status:error.status,message:error.message});res.status(Number(error.status)||500).json({error:error.message||'Не удалось синхронизировать Эвотор'})}}
async function evotorDisconnect(req,res){try{await ensureSchema();await pool.query("delete from owner_integrations where owner_id=$1 and provider='evotor'",[req.integrationOwner.id]);res.json({ok:true,connected:false})}catch(error){console.error('Evotor disconnect failed',error);res.status(500).json({error:'Не удалось отключить Эвотор'})}}
express.application.listen=function(...args){if(!this.__evotorIntegrationInstalled){this.__evotorIntegrationInstalled=true;this.get('/api/v1/owner/integrations/evotor',ownerAuth,evotorStatus);this.post('/api/v1/owner/integrations/evotor/connect',ownerAuth,connectLimit,express.json({limit:'8kb'}),evotorConnect);this.post('/api/v1/owner/integrations/evotor/test',ownerAuth,connectLimit,evotorTest);this.post('/api/v1/owner/integrations/evotor/sync',ownerAuth,connectLimit,evotorSync);this.post('/api/v1/owner/integrations/evotor/disconnect',ownerAuth,evotorDisconnect)}return originalListen.apply(this,args)};
if(!globalThis.__lfEvotorSyncTimer){globalThis.__lfEvotorSyncTimer=true;const run=async()=>{try{await ensureSchema();const rows=(await pool.query("select owner_id,secret_enc,meta from owner_integrations where provider='evotor' limit 200")).rows;for(const row of rows){try{const token=decryptSecret(row.secret_enc,jwtSecret);await syncEvotor(row.owner_id,token,row.meta||{})}catch(error){console.error('Evotor background sync failed',{ownerId:row.owner_id,status:error.status,message:error.message})}}}catch(error){console.error('Evotor scheduler failed',error.message)}};const timer=setTimeout(()=>{run();const interval=setInterval(run,evotorInterval);interval.unref?.()},30000);timer.unref?.()}

/* Бизнес.Ру Open API: поиск контрагента по карте и бонусному балансу. */
const businessLookupLimit=rateLimit({windowMs:60*1000,limit:45,standardHeaders:true,legacyHeaders:false,keyGenerator:req=>String(req.integrationOwner?.id||req.businessOwnerId||req.ip),message:{error:'Слишком много поисковых запросов'}});
const businessAccountOk=value=>/^[a-z0-9][a-z0-9-]{0,40}$/i.test(String(value||''));
const businessAppIdOk=value=>/^\d{1,20}$/.test(String(value||''));
const businessSecretOk=value=>typeof value==='string'&&value.length>=16&&value.length<=128&&!/[\s\x00-\x1f\x7f]/.test(value);
const businessCodeOk=value=>{const s=String(value||'').trim();return s.length>0&&s.length<=120&&!/[\x00-\x1f\x7f]/.test(s)};
function businessFormValue(value){if(value===null||value===undefined)return'';if(Array.isArray(value))return value.map((item,index)=>encodeURIComponent(String(index))+'='+encodeURIComponent(String(item??''))).join('&');return encodeURIComponent(String(value))}
function businessQuery(params={}){return Object.keys(params).sort().map(key=>businessFormValue(key)+'='+businessFormValue(params[key])).join('&')}
function businessBase(account){return'https://'+String(account).toLowerCase()+'.business.ru/api/rest/'}
function businessCredentials(value){try{const parsed=JSON.parse(String(value||''));if(!businessAccountOk(parsed.account)||!businessAppIdOk(parsed.appId)||!businessSecretOk(parsed.secret))return null;return{account:String(parsed.account).toLowerCase(),appId:String(parsed.appId),secret:String(parsed.secret),token:typeof parsed.token==='string'?parsed.token:''}}catch{return null}}
function businessRows(payload){if(Array.isArray(payload))return payload;if(Array.isArray(payload?.result))return payload.result;if(payload?.result&&typeof payload.result==='object')return[payload.result];return[]}
async function businessRaw(credentials,method,model,params={},token=''){const safeModel=String(model||'').replace(/[^a-z0-9_-]/gi,'');if(!safeModel)throw Object.assign(Error('Недопустимая модель Бизнес.Ру'),{status:400});const queryParams={...params,app_id:credentials.appId},baseQuery=businessQuery(queryParams),signed=crypto.createHash('md5').update(String(token)+credentials.secret+baseQuery).digest('hex'),bodyParams={...queryParams,app_psw:signed},url=businessBase(credentials.account)+safeModel+'.json',controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const options={method,redirect:'error',headers:{Accept:'application/json','User-Agent':'LoyaltyFlow/1.0 BusinessRuIntegration/1'}};if(method==='GET')options.url=url+'?'+businessQuery(bodyParams);else{options.body=businessQuery(bodyParams);options.headers['Content-Type']='application/x-www-form-urlencoded'}const response=await fetch(options.url||url,options);const raw=(await response.text()).slice(0,4000000);let data={};try{data=raw?JSON.parse(raw):{}}catch{throw Object.assign(Error('Бизнес.Ру вернул некорректный ответ'),{status:502})}if(response.status===401)throw Object.assign(Error('Токен Бизнес.Ру истёк'),{status:401});if(!response.ok||data?.status==='error')throw Object.assign(Error(String(data?.error_text||data?.message||'Бизнес.Ру отклонил запрос').replace(/[\x00-\x1f\x7f]+/g,' ').slice(0,300)),{status:response.status>=400&&response.status<500?400:502});return data}catch(error){if(error.name==='AbortError')throw Object.assign(Error('Бизнес.Ру не ответил за 10 секунд'),{status:504});throw error}finally{clearTimeout(timer)}}
async function businessRepair(credentials){const data=await businessRaw(credentials,'GET','repair',{},'');const token=String(data?.token||'');if(!/^[a-zA-Z0-9]{16,128}$/.test(token))throw Object.assign(Error('Бизнес.Ру не выдал токен доступа'),{status:502});return token}
async function businessRequest(credentials,method,model,params={}){let token=credentials.token||await businessRepair(credentials);try{return{data:await businessRaw(credentials,method,model,params,token),token}}catch(error){if(error.status!==401)throw error;token=await businessRepair(credentials);return{data:await businessRaw(credentials,method,model,params,token),token}}}
async function businessInspect(credentials){const partners=await businessRequest(credentials,'GET','partners',{count_only:1});return{account:credentials.account,checkedAt:new Date().toISOString(),partnersAvailable:!partners.data?.error_code,cardModel:'discountcards',bonusModel:'discountcardbonuses'}}
async function businessIntegrationRow(ownerId){await ensureSchema();return(await pool.query("select secret_enc,meta,updated_at from owner_integrations where owner_id=$1 and provider='businessru'",[ownerId])).rows[0]}
async function businessStatus(req,res){try{const row=await businessIntegrationRow(req.integrationOwner.id);res.json({provider:'businessru',connected:Boolean(row),meta:row?.meta||{},updatedAt:row?.updated_at||null})}catch(error){console.error('BusinessRu status failed',error);res.status(500).json({error:'Не удалось загрузить состояние Бизнес.Ру'})}}
async function businessConnect(req,res){try{const account=String(req.body?.account||'').trim().toLowerCase(),appId=String(req.body?.appId||'').trim(),secret=String(req.body?.secret||'');if(!businessAccountOk(account))return res.status(400).json({error:'Укажите корректное имя аккаунта Бизнес.Ру'});if(!businessAppIdOk(appId))return res.status(400).json({error:'Укажите корректный ID интеграции'});if(!businessSecretOk(secret))return res.status(400).json({error:'Укажите корректный секретный ключ'});let credentials={account,appId,secret,token:''};credentials.token=await businessRepair(credentials);const meta=await businessInspect(credentials);await pool.query("insert into owner_integrations(owner_id,provider,secret_enc,meta) values($1,'businessru',$2,$3::jsonb) on conflict(owner_id,provider) do update set secret_enc=excluded.secret_enc,meta=excluded.meta,updated_at=now()",[req.integrationOwner.id,encryptSecret(JSON.stringify(credentials),jwtSecret),JSON.stringify(meta)]);res.json({ok:true,connected:true,meta})}catch(error){console.error('BusinessRu connect failed',{status:error.status,message:error.message});res.status(Number(error.status)||500).json({error:error.message||'Не удалось подключить Бизнес.Ру'})}}
async function businessTest(req,res){try{const row=await businessIntegrationRow(req.integrationOwner.id);if(!row)return res.status(404).json({error:'Сначала подключите Бизнес.Ру'});const credentials=businessCredentials(decryptSecret(row.secret_enc,jwtSecret));if(!credentials)return res.status(500).json({error:'Сохранённые данные интеграции повреждены'});const result=await businessRequest(credentials,'GET','partners',{count_only:1});const meta={...(row.meta||{}),account:credentials.account,checkedAt:new Date().toISOString(),partnersAvailable:!result.data?.error_code};await pool.query("update owner_integrations set secret_enc=$1,meta=$2::jsonb,updated_at=now() where owner_id=$3 and provider='businessru'",[encryptSecret(JSON.stringify({...credentials,token:result.token}),jwtSecret),JSON.stringify(meta),req.integrationOwner.id]);res.json({ok:true,connected:true,meta})}catch(error){console.error('BusinessRu test failed',{status:error.status,message:error.message});res.status(Number(error.status)||500).json({error:error.message||'Не удалось проверить Бизнес.Ру'})}}
async function businessDisconnect(req,res){try{await ensureSchema();await pool.query("delete from owner_integrations where owner_id=$1 and provider='businessru'",[req.integrationOwner.id]);res.json({ok:true,connected:false})}catch(error){console.error('BusinessRu disconnect failed',error);res.status(500).json({error:'Не удалось отключить Бизнес.Ру'})}}
async function businessFindCustomer(ownerId,code){const row=await businessIntegrationRow(ownerId);if(!row)throw Object.assign(Error('Сначала подключите Бизнес.Ру'),{status:404});const credentials=businessCredentials(decryptSecret(row.secret_enc,jwtSecret));if(!credentials)throw Object.assign(Error('Сохранённые данные интеграции повреждены'),{status:500});let cardResult=await businessRequest(credentials,'GET','discountcards',{num:code,limit:10,extended:1}),cards=businessRows(cardResult.data);if(!cards.length)return{notFound:true};const card=cards[0],partnerResult=card.partner_id?await businessRequest(credentials,'GET','partners',{id:card.partner_id,limit:1,extended:1}):{data:{},token:cardResult.token},partner=businessRows(partnerResult.data)[0]||{};let balance=Number(card.bonus_sum);try{const bonusResult=await businessRequest({...credentials,token:partnerResult.token||cardResult.token},'GET','discountcardbonuses',{discount_card_id:card.id,active:1,limit:100}),bonusRows=businessRows(bonusResult.data),sum=bonusRows.reduce((total,item)=>total+(Number(item.value)||0),0);if(!Number.isFinite(balance))balance=sum;cardResult.token=bonusResult.token}catch(error){if(!Number.isFinite(balance))balance=0}const contactRows=Array.isArray(partner.contactinfo)?partner.contactinfo:Array.isArray(partner.contact_info)?partner.contact_info:[],phone=String(contactRows.find(item=>item?.phone||item?.contact_info)?.phone||contactRows.find(item=>item?.phone||item?.contact_info)?.contact_info||partner.phone||'');await pool.query("update owner_integrations set secret_enc=$1,updated_at=now() where owner_id=$2 and provider='businessru'",[encryptSecret(JSON.stringify({...credentials,token:cardResult.token}),jwtSecret),ownerId]);return{customer:{name:String(partner.name||partner.full_name||'Клиент').slice(0,160),phone:phone.slice(0,40),cardNumber:String(card.num||code).slice(0,120),balance:Number.isFinite(balance)?balance:0,externalId:String(card.id||'').slice(0,80),source:'businessru'}}}
async function businessOwnerLookup(req,res){try{const code=String(req.body?.code||'').trim();if(!businessCodeOk(code))return res.status(400).json({error:'Введите номер QR или карты'});const result=await businessFindCustomer(req.integrationOwner.id,code);if(result.notFound)return res.status(404).json({error:'Клиент с таким номером карты не найден'});res.json({ok:true,...result})}catch(error){console.error('BusinessRu lookup failed',{status:error.status,message:error.message});res.status(Number(error.status)||500).json({error:error.message||'Не удалось найти клиента в Бизнес.Ру'})}}
function businessCashierCookie(req){const value=String(req.headers.cookie||'');for(const name of['__Host-lf_cashier','lf_cashier']){const match=value.match(new RegExp('(?:^|;\\s*)'+name+'=([^;]+)'));if(match)try{return decodeURIComponent(match[1])}catch{return''}}return''}
async function businessCashierAuth(req,res,next){try{const session=verifySession(businessCashierCookie(req),jwtSecret);if(!session)return res.status(401).json({error:'Войдите как кассир'});const row=(await pool.query('select c.id,c.owner_id,c.active,c.session_version,u.status owner_status,u.trial_end owner_trial_end from cashier_accounts c join users u on u.id=c.owner_id where c.id=$1',[session.id])).rows[0];if(!row||!row.active||Number(session.sv||0)!==Number(row.session_version||0))return res.status(401).json({error:'Сессия кассира недействительна'});if(['pending_admin','email_pending','blocked','disabled','rejected','frozen'].includes(String(row.owner_status||'').toLowerCase())||row.owner_trial_end&&new Date(row.owner_trial_end).getTime()<Date.now())return res.status(403).json({error:'Аккаунт компании недоступен'});req.businessOwnerId=row.owner_id;res.setHeader('Cache-Control','no-store');next()}catch(error){console.error('BusinessRu cashier auth failed',error);res.status(503).json({error:'Не удалось проверить доступ кассира'})}}
async function businessCashierLookup(req,res){try{const code=String(req.body?.code||'').trim();if(!businessCodeOk(code))return res.status(400).json({error:'Введите номер QR или карты'});const result=await businessFindCustomer(req.businessOwnerId,code);if(result.notFound)return res.status(404).json({error:'Клиент с таким номером карты не найден'});res.json({ok:true,...result})}catch(error){console.error('BusinessRu cashier lookup failed',{status:error.status,message:error.message});res.status(Number(error.status)||500).json({error:error.message||'Не удалось найти клиента в Бизнес.Ру'})}}
const businessOriginalListen=express.application.listen;express.application.listen=function(...args){if(!this.__businessRuIntegrationInstalled){this.__businessRuIntegrationInstalled=true;this.get('/api/v1/owner/integrations/businessru',ownerAuth,businessStatus);this.post('/api/v1/owner/integrations/businessru/connect',ownerAuth,connectLimit,express.json({limit:'16kb'}),businessConnect);this.post('/api/v1/owner/integrations/businessru/test',ownerAuth,connectLimit,businessTest);this.post('/api/v1/owner/integrations/businessru/disconnect',ownerAuth,businessDisconnect);this.post('/api/v1/owner/integrations/businessru/lookup',ownerAuth,businessLookupLimit,express.json({limit:'8kb'}),businessOwnerLookup);this.post('/api/v1/cashier/businessru/customer',businessCashierAuth,businessLookupLimit,express.json({limit:'8kb'}),businessCashierLookup)}return businessOriginalListen.apply(this,args)};
