import express from 'express';
import rateLimit from 'express-rate-limit';
import pg from 'pg';
import {verifyRegistrationCaptcha} from './registration-security.js';
import {loginSecurityContext} from './login-security-context.js';
import {verifySession} from './security.js';
const {Pool}=pg,pool=new Pool({connectionString:process.env.DATABASE_URL}),jwtSecret=String(process.env.JWT_SECRET||''),publicOrigin=(()=>{try{return new URL(process.env.PUBLIC_APP_URL).origin}catch{return''}})(),originalInit=express.application.init,originalPost=express.application.post,originalListen=express.application.listen;
let sessionSchemaReady=false;
async function ensureSessionSchema(){if(sessionSchemaReady)return true;try{await pool.query('alter table users add column if not exists session_version integer not null default 0');sessionSchemaReady=true;return true}catch{return false}}
function cookieToken(req){const value=String(req.headers.cookie||'');for(const name of['__Host-lf_session','lf_session']){const match=value.match(new RegExp('(?:^|;\\s*)'+name+'=([^;]+)'));if(match)try{return decodeURIComponent(match[1])}catch{return''}}return''}
function cookieLine(name,token,maxAge,secure){return `${name}=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${maxAge}; Priority=High${secure?'; Secure':''}`}
function secureCookies(req,token,maxAge=86400){const secure=req.secure||String(req.get('x-forwarded-proto')||'').split(',')[0].trim()==='https';if(token)return[cookieLine(secure?'__Host-lf_session':'lf_session',token,maxAge,secure)];return[cookieLine('__Host-lf_session','',0,true),cookieLine('lf_session','',0,false)]}
function originAllowed(req){const origin=String(req.get('Origin')||'');return !origin||!publicOrigin||origin===publicOrigin}
async function requestSecurity(req,res,next){if(req.path.startsWith('/api/v1/admin/'))return res.status(404).json({error:'Маршрут отключён'});const authorization=String(req.headers.authorization||''),cookie=cookieToken(req),usingCookie=Boolean(cookie)&&(!authorization||/^Bearer\s+cookie-session$/i.test(authorization));if(usingCookie)req.headers.authorization='Bearer '+cookie;else if(/^Bearer\s+cookie-session$/i.test(authorization))delete req.headers.authorization;if(usingCookie&&!['GET','HEAD','OPTIONS'].includes(req.method)&&!originAllowed(req))return res.status(403).json({error:'Запрос отклонён проверкой источника'});if(req.path.startsWith('/api/v1/auth/'))res.setHeader('Cache-Control','no-store');const protectedPath=req.path==='/api/v1/auth/me'||req.path.startsWith('/api/v1/owner/');if(!protectedPath)return next();const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,''),session=verifySession(token,jwtSecret);if(!session)return next();if(!await ensureSessionSchema())return res.status(503).json({error:'Не удалось проверить сессию'});const user=(await pool.query('select id,email,status,trial_end,admin_frozen,session_version from users where id=$1',[session.id])).rows[0];if(!user||Number(session.sv||0)!==Number(user.session_version||0))return res.status(401).json({error:'Сессия отозвана. Войдите снова.'});const status=String(user.status||'').toLowerCase();if(user.admin_frozen||['pending_admin','email_pending','blocked','disabled','rejected','frozen'].includes(status)||user.trial_end&&new Date(user.trial_end).getTime()<Date.now())return res.status(403).json({error:'Аккаунт заблокирован, не активирован или срок доступа истёк'});req.securityUser=user;if(!usingCookie&&token)res.setHeader('Set-Cookie',secureCookies(req,token));next()}
express.application.init=function(...args){const result=originalInit.apply(this,args);this.set('trust proxy','loopback');this.disable('x-powered-by');this.use(requestSecurity);return result};
const bad=(res,message)=>res.status(400).json({error:message});function validateRegistration(req,res,next){const body=req.body||{},fullName=String(body.fullName||'').trim().replace(/\s+/g,' '),company=String(body.company||'').trim().replace(/\s+/g,' '),city=String(body.city||'').trim().replace(/\s+/g,' '),email=String(body.email||'').trim().toLowerCase(),phone=String(body.phone||'').trim(),password=String(body.password||''),age=Number(body.age);if(fullName.length<2||fullName.length>120)return bad(res,'Имя должно содержать от 2 до 120 символов');if(company.length<2||company.length>120)return bad(res,'Название компании должно содержать от 2 до 120 символов');if(city.length<2||city.length>80)return bad(res,'Название города должно содержать от 2 до 80 символов');if(!/^[^\s@]{1,64}@[^\s@]{1,190}\.[^\s@]{2,63}$/.test(email)||email.length>254)return bad(res,'Введите корректный email');if(!/^\+[1-9]\d{7,14}$/.test(phone))return bad(res,'Введите телефон в международном формате');if(!Number.isInteger(age)||age<14||age>100)return bad(res,'Укажите возраст от 14 до 100 лет');if(password.length<8||password.length>128)return bad(res,'Пароль должен содержать от 8 до 128 символов');req.body={...body,fullName,company,city,email,phone,password,age};next()}function validateLogin(req,res,next){const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');if(email.length>254||password.length>128)return bad(res,'Неверный email или пароль');req.body={...(req.body||{}),email,password};next()}function validateCode(req,res,next){const email=String(req.body?.email||'').trim().toLowerCase(),code=String(req.body?.code||'');if(email.length>254||!/^[0-9]{6}$/.test(code))return bad(res,'Неверный или просроченный код');req.body={...(req.body||{}),email,code};next()}

const cleanText=(value,max)=>String(value??'').trim().replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').slice(0,max);
function safeImage(value,max=1000){const image=String(value||'').trim();if(!image)return'';if(/^https:\/\/[^\s]+$/i.test(image)&&image.length<=max)return image;if(/^data:image\/(?:png|jpeg|webp);base64,[a-z0-9+/=]+$/i.test(image)&&image.length<=700000)return image;return null}
function sanitizeMiniapp(req,res,next){const input=req.body?.design;if(!input||typeof input!=='object'||Array.isArray(input))return bad(res,'Некорректные настройки Mini App');const design={};for(const key of['qr','profile','offers','history','catalog','glass','shadow'])if(key in input)design[key]=Boolean(input[key]);for(const key of['accent','header','background','card','text'])if(key in input&&/^#[0-9a-f]{3,8}$/i.test(String(input[key])))design[key]=String(input[key]);for(const[key,min,max]of[['fontSize',10,30],['titleSize',14,60],['radius',0,48],['spacing',4,40]])if(key in input)design[key]=Math.min(max,Math.max(min,Number(input[key])||min));for(const[key,max]of Object.entries({name:120,title:160,description:2000,balanceLabel:80,buttonText:120,menuButtonText:64}))if(key in input)design[key]=cleanText(input[key],max);const logo=safeImage(input.logo);if(logo===null)return bad(res,'Логотип должен быть HTTPS-изображением или PNG/JPEG/WebP до 700 КБ');if(logo)design.logo=logo;if(input.loyalty&&typeof input.loyalty==='object'&&!Array.isArray(input.loyalty))design.loyalty=input.loyalty;const rows=Array.isArray(input.products)?input.products:[];if(rows.length>2000)return bad(res,'В каталоге не может быть больше 2000 товаров');design.products=[];for(const row of rows){const id=cleanText(row?.id,80),name=cleanText(row?.name,160),category=cleanText(row?.category,100),description=cleanText(row?.description,2000),image=safeImage(row?.image),price=Number(row?.price),bonus=Number(row?.bonus),stock=Number(row?.stock);if(!/^[a-z0-9_-]{1,80}$/i.test(id)||!name)return bad(res,'У товара некорректный идентификатор или название');if(image===null)return bad(res,'Изображения товаров должны использовать HTTPS или безопасный PNG/JPEG/WebP');if(!Number.isFinite(price)||price<0||price>1e9||!Number.isFinite(bonus)||bonus<0||bonus>1e6||!Number.isFinite(stock)||stock<0||stock>1e9)return bad(res,'Проверьте цену, бонусы и остаток товара');design.products.push({id,name,category,description,image:image||'',price,bonus:Math.floor(bonus),stock:Math.floor(stock)})}req.body={...(req.body||{}),design};next()}
function validateAdjustment(req,res,next){const amount=Math.trunc(Number(req.body?.amount)||0);if(!amount||Math.abs(amount)>1000000)return bad(res,'Корректировка должна быть от -1 000 000 до 1 000 000 бонусов');next()}

const loginCaptcha=async(req,res,next)=>{try{if(!await verifyRegistrationCaptcha(req.body?.turnstileToken,req.ip,'login'))return res.status(400).json({error:'Проверка безопасности не пройдена. Обновите страницу и попробуйте снова.'});loginSecurityContext.run(true,()=>next())}catch(error){console.error(error);res.status(Number(error.status)||500).json({error:'Не удалось выполнить проверку безопасности'})}},verifyAccountLimit=rateLimit({windowMs:15*60*1000,limit:8,standardHeaders:true,legacyHeaders:false,skipSuccessfulRequests:true,keyGenerator:req=>String(req.body?.email||'').trim().toLowerCase().slice(0,320)||'missing-email',message:{error:'Слишком много неверных кодов для этого аккаунта. Попробуйте позже.'}});function issueCookie(req,res,next){const send=res.json.bind(res);res.json=body=>{if(body?.token){res.setHeader('Set-Cookie',secureCookies(req,body.token));}return send(body)};next()}
express.application.post=function(path,...handlers){if(String(path).startsWith('/api/v1/admin/'))return originalPost.call(this,path,(req,res)=>res.status(404).json({error:'Маршрут отключён'}));if(path==='/api/v1/owner/miniapp')return originalPost.call(this,path,sanitizeMiniapp,...handlers);if(path==='/api/v1/owner/loyalty/adjust')return originalPost.call(this,path,validateAdjustment,...handlers);if(path==='/api/v1/public/:tenant/loyalty/purchase')return originalPost.call(this,path,(req,res)=>res.status(503).json({error:'Оплата временно отключена до подключения проверенной платёжной системы'}));if(path==='/api/v1/sync/:secret'){originalPost.call(this,'/api/v1/sync',(req,res,next)=>{req.params.secret=String(req.get('X-Sync-Secret')||'');next()},...handlers);return originalPost.call(this,path,(req,res)=>res.status(410).json({error:'Передача секрета в URL отключена'}))}if(path==='/api/v1/auth/register'){const[byIp,...rest]=handlers;return originalPost.call(this,path,byIp,validateRegistration,...rest)}if(path==='/api/v1/auth/login'){const[byIp,...rest]=handlers;return originalPost.call(this,path,byIp,validateLogin,loginCaptcha,issueCookie,...rest)}if(path==='/api/v1/auth/verify'){const[byIp,...rest]=handlers;return originalPost.call(this,path,byIp,validateCode,verifyAccountLimit,...rest)}return originalPost.call(this,path,...handlers)};
express.application.listen=function(...args){if(!this.__secureLogoutInstalled){this.__secureLogoutInstalled=true;originalPost.call(this,'/api/v1/auth/logout',(req,res)=>{res.setHeader('Set-Cookie',secureCookies(req,'',0));res.setHeader('Clear-Site-Data','"storage"');res.setHeader('Cache-Control','no-store');res.json({ok:true})})}return originalListen.apply(this,args)};
