import crypto from 'node:crypto';
import {isLoginCaptchaVerified} from './login-security-context.js';
const production=String(process.env.NODE_ENV||'').toLowerCase()==='production';
export const hash=value=>crypto.createHash('sha256').update(String(value)).digest('hex');
export const b64=value=>Buffer.from(value).toString('base64url');
export function passwordHash(password){const salt=crypto.randomBytes(16).toString('hex');return `${salt}:${crypto.scryptSync(password,salt,64).toString('hex')}`}
function comparePassword(password,stored){try{const [salt,value,...extra]=String(stored||'').split(':');if(!salt||!value||extra.length)return false;const actual=crypto.scryptSync(String(password),salt,64),expected=Buffer.from(value,'hex');return actual.length===expected.length&&crypto.timingSafeEqual(actual,expected)}catch{return false}}
export function passwordOk(password,stored){if(production&&!isLoginCaptchaVerified())return false;return comparePassword(password,stored)}
export function passwordOkTrusted(password,stored){return comparePassword(password,stored)}
function requireSecret(secret,name){if(!secret)throw new Error(`${name} is required`);return secret}
export function signSession(user,secret,ttlMs=86_400_000,now=Date.now()){requireSecret(secret,'JWT_SECRET');const body=b64(JSON.stringify({id:user.id,email:user.email,sv:Number(user.session_version||0),exp:now+ttlMs}));return `${body}.${b64(crypto.createHmac('sha256',secret).update(body).digest())}`}
export function verifySession(token,secret,now=Date.now()){try{requireSecret(secret,'JWT_SECRET');const parts=String(token||'').split('.');if(parts.length!==2)return null;const [body,signature]=parts,actual=Buffer.from(signature,'base64url'),expected=crypto.createHmac('sha256',secret).update(body).digest();if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))return null;const data=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));return data?.id&&Number.isFinite(data.exp)&&data.exp>now?data:null}catch{return null}}
function encryptionKey(secret){return crypto.createHash('sha256').update(requireSecret(secret,'BOT_TOKEN_ENCRYPTION_KEY')).digest()}
function configuredEncryptionSecret(legacySecret){return String(process.env.BOT_TOKEN_ENCRYPTION_KEY||legacySecret||'')}
export function encryptSecret(text,legacySecret){const secret=configuredEncryptionSecret(legacySecret),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',encryptionKey(secret),iv),data=Buffer.concat([cipher.update(String(text),'utf8'),cipher.final()]);return[iv.toString('hex'),cipher.getAuthTag().toString('hex'),data.toString('hex')].join(':')}
function decryptWith(value,secret){const [iv,tag,data,...extra]=String(value||'').split(':');if(!iv||!tag||!data||extra.length)throw new Error('Invalid encrypted value');const decipher=crypto.createDecipheriv('aes-256-gcm',encryptionKey(secret),Buffer.from(iv,'hex'));decipher.setAuthTag(Buffer.from(tag,'hex'));return Buffer.concat([decipher.update(Buffer.from(data,'hex')),decipher.final()]).toString('utf8')}
export function decryptSecret(value,legacySecret){const configured=configuredEncryptionSecret(legacySecret);try{return decryptWith(value,configured)}catch(error){if(configured!==String(legacySecret||''))return decryptWith(value,String(legacySecret||''));throw error}}
export function parseAllowedOrigins(publicAppUrl,extra=''){const origins=new Set(String(extra).split(',').map(x=>x.trim()).filter(Boolean));if(publicAppUrl){try{origins.add(new URL(publicAppUrl).origin)}catch{}}return origins}
export function verifyTelegramInitData(initData,botToken,{maxAgeSeconds=86_400,nowSeconds=Math.floor(Date.now()/1000)}={}){try{if(!initData||!botToken)return null;const params=new URLSearchParams(initData),received=params.get('hash'),authDate=Number(params.get('auth_date'));if(!received||!Number.isInteger(authDate)||authDate<=0||authDate>nowSeconds+30||nowSeconds-authDate>maxAgeSeconds)return null;params.delete('hash');const check=[...params.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([key,value])=>`${key}=${value}`).join('\n'),secret=crypto.createHmac('sha256','WebAppData').update(botToken).digest(),expected=crypto.createHmac('sha256',secret).update(check).digest('hex'),actual=Buffer.from(received,'hex'),expectedBuffer=Buffer.from(expected,'hex');if(actual.length!==expectedBuffer.length||!crypto.timingSafeEqual(actual,expectedBuffer))return null;const user=params.get('user');return user?JSON.parse(user):{}}catch{return null}}
