import express from 'express';
import rateLimit from 'express-rate-limit';
import pg from 'pg';
import {verifyRegistrationCaptcha} from './registration-security.js';
import {loginSecurityContext} from './login-security-context.js';
import {verifySession} from './security.js';
const {Pool}=pg,pool=new Pool({connectionString:process.env.DATABASE_URL}),jwtSecret=String(process.env.JWT_SECRET||''),originalInit=express.application.init,originalPost=express.application.post,originalListen=express.application.listen;
let sessionSchemaReady=false;
async function ensureSessionSchema(){if(sessionSchemaReady)return true;try{await pool.query('alter table users add column if not exists session_version integer not null default 0');sessionSchemaReady=true;return true}catch{return false}}
function cookieToken(req){const match=String(req.headers.cookie||'').match(/(?:^|;\s*)lf_session=([^;]+)/);try{return match?decodeURIComponent(match[1]):''}catch{return''}}
function secureCookie(req,token,maxAge=86400){const secure=req.secure||String(req.get('x-forwarded-proto')||'').split(',')[0].trim()==='https';return `lf_session=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${maxAge}${secure?'; Secure':''}`}
async function requestSecurity(req,res,next){const authorization=String(req.headers.authorization||'');if(!authorization||/^Bearer\s+cookie-session$/i.test(authorization)){const token=cookieToken(req);if(token)req.headers.authorization='Bearer '+token;else delete req.headers.authorization}if(req.path.startsWith('/api/v1/auth/'))res.setHeader('Cache-Control','no-store');const protectedPath=req.path==='/api/v1/auth/me'||req.path.startsWith('/api/v1/owner/');if(!protectedPath)return next();const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,''),session=verifySession(token,jwtSecret);if(!session)return next();if(!await ensureSessionSchema())return res.status(503).json({error:'Не удалось проверить сессию'});const user=(await pool.query('select session_version from users where id=$1',[session.id])).rows[0];if(!user||Number(session.sv||0)!==Number(user.session_version||0))return res.status(401).json({error:'Сессия отозвана. Войдите снова.'});next()}
express.application.init=function(...args){const result=originalInit.apply(this,args);this.set('trust proxy','loopback');this.disable('x-powered-by');this.use(requestSecurity);return result};
const bad=(res,message)=>res.status(400).json({error:message});
function validateRegistration(req,res,next){const body=req.body||{},fullName=String(body.fullName||'').trim().replace(/\s+/g,' '),company=String(body.company||'').trim().replace(/\s+/g,' '),city=String(body.city||'').trim().replace(/\s+/g,' '),email=String(body.email||'').trim().toLowerCase(),phone=String(body.phone||'').trim(),password=String(body.password||''),age=Number(body.age);if(fullName.length<2||fullName.length>120)return bad(res,'Имя должно содержать от 2 до 120 символов');if(company.length<2||company.length>120)return bad(res,'Название компании должно содержать от 2 до 120 символов');if(city.length<2||city.length>80)return bad(res,'Название города должно содержать от 2 до 80 символов');if(!/^[^\s@]{1,64}@[^\s@]{1,190}\.[^\s@]{2,63}$/.test(email)||email.length>254)return bad(res,'Введите корректный email');if(!/^\+[1-9]\d{7,14}$/.test(phone))return bad(res,'Введите телефон в международном формате');if(!Number.isInteger(age)||age<14||age>100)return bad(res,'Укажите возраст от 14 до 100 лет');if(password.length<8||password.length>128)return bad(res,'Пароль должен содержать от 8 до 128 символов');req.body={...body,fullName,company,city,email,phone,password,age};next()}
function validateLogin(req,res,next){const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');if(email.length>254||password.length>128)return bad(res,'Неверный email или пароль');req.body={...(req.body||{}),email,password};next()}
function validateCode(req,res,next){const email=String(req.body?.email||'').trim().toLowerCase(),code=String(req.body?.code||'');if(email.length>254||!/^[0-9]{6}$/.test(code))return bad(res,'Неверный или просроченный код');req.body={...(req.body||{}),email,code};next()}
const loginCaptcha=async(req,res,next)=>{try{if(!await verifyRegistrationCaptcha(req.body?.turnstileToken,req.ip,'login'))return res.status(400).json({error:'Проверка безопасности не пройдена. Обновите страницу и попробуйте снова.'});loginSecurityContext.run(true,()=>next())}catch(error){console.error(error);res.status(Number(error.status)||500).json({error:'Не удалось выполнить проверку безопасности'})}};
const verifyAccountLimit=rateLimit({windowMs:15*60*1000,limit:8,standardHeaders:true,legacyHeaders:false,skipSuccessfulRequests:true,keyGenerator:req=>String(req.body?.email||'').trim().toLowerCase().slice(0,320)||'missing-email',message:{error:'Слишком много неверных кодов для этого аккаунта. Попробуйте позже.'}});
function issueCookie(req,res,next){const send=res.json.bind(res);res.json=body=>{if(body?.token){res.setHeader('Set-Cookie',secureCookie(req,body.token));body={...body,token:'cookie-session'}}return send(body)};next()}
express.application.post=function(path,...handlers){if(path==='/api/v1/public/:tenant/loyalty/purchase')return originalPost.call(this,path,(req,res)=>res.status(503).json({error:'Оплата временно отключена до подключения проверенной платёжной системы'}));if(path==='/api/v1/sync/:secret'){originalPost.call(this,'/api/v1/sync',(req,res,next)=>{req.params.secret=String(req.get('X-Sync-Secret')||'');next()},...handlers);return originalPost.call(this,path,(req,res)=>res.status(410).json({error:'Передача секрета в URL отключена'}))}if(path==='/api/v1/auth/register'){const[byIp,...rest]=handlers;return originalPost.call(this,path,byIp,validateRegistration,...rest)}if(path==='/api/v1/auth/login'){const[byIp,...rest]=handlers;return originalPost.call(this,path,byIp,validateLogin,loginCaptcha,issueCookie,...rest)}if(path==='/api/v1/auth/verify'){const[byIp,...rest]=handlers;return originalPost.call(this,path,byIp,validateCode,verifyAccountLimit,...rest)}return originalPost.call(this,path,...handlers)};
express.application.listen=function(...args){if(!this.__secureLogoutInstalled){this.__secureLogoutInstalled=true;originalPost.call(this,'/api/v1/auth/logout',(req,res)=>{res.setHeader('Set-Cookie',secureCookie(req,'',0));res.setHeader('Clear-Site-Data','"storage"');res.setHeader('Cache-Control','no-store');res.json({ok:true})})}return originalListen.apply(this,args)};
